
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace M_Kurs_Shool
{

using System;
    using System.Collections.Generic;
    
public partial class Contract
{

    public Nullable<int> NumberContract { get; set; }

    public int ContactTypeId { get; set; }

    public Nullable<int> Summa { get; set; }

    public string Avatat { get; set; }

    public Nullable<int> ContactTime { get; set; }

    public int ClientId { get; set; }

    public int id { get; set; }



    public virtual Client Client { get; set; }

    public virtual ContractType ContractType { get; set; }

}

}
