

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace M_Kurs_Shool
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class foreignschool_kpEntities : DbContext
{
    public foreignschool_kpEntities()
        : base("name=foreignschool_kpEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Contract> Contract { get; set; }

    public virtual DbSet<ContractType> ContractType { get; set; }

}

}

